name: wecareapp
description: "WeCare App"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  crypto: ^3.0.6
  file_picker: ^10.3.2
  flutter:
    sdk: flutter
  geolocator: ^13.0.1
  shared_preferences: ^2.5.3
  supabase_flutter: ^2.10.0
  url_launcher: ^6.3.1
  qr_flutter: ^4.1.0
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/lang/en.json
    - assets/lang/tl.json
    - assets/lang/ceb.json